name: typehints check

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  mypy:
    name: mypy typehints check
    runs-on: 'ubuntu-20.04'
    steps:
    - name: checkout software
      uses: actions/checkout@v2
      with:
        path: software
    - name: checkout retype
      uses: actions/checkout@v2
      with:
        path: retype
        repository: ambv/retype
        ref: fe1a22f31d9a1e84da2311f86830d807015d1bf0
      # ref: 17.12.0
    - name: 'refresh install'
      run: |
        sudo apt-get update --fix-missing
    - name: 'install python3 mypy'
      run: |
        sudo apt-get install --fix-broken --ignore-missing python3-typed-ast mypy
    - name: 'show mypy directories'
      run: |
        find . -type d
        mypy --version
    - name: 'make type (mypy strict type checking)'
      id: check
      run: |
        make type -C software
